# Generated by Django 5.1.2 on 2024-11-16 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_order_slug_alter_order_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
