# Generated by Django 5.1.2 on 2024-11-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_remove_product_tags_delete_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profileimg',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to='base/images/'),
        ),
    ]
