# Generated by Django 5.1.2 on 2024-11-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_orderitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='name',
        ),
    ]
